name: Tests Py 3.7

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install pytest-cov

      - name: Install DRYML
        run: |
          python setup.py install

      - name: Run Tests
        run: |
          ./tests.sh --cov-report=xml --cov-report=html
