name: Tests Py 3.10

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r test_requirements.txt

      - name: Install DRYML
        run: |
          python setup.py install

      - name: Run Tests
        run: |
          ./tests.sh --cov-report=xml --cov-report=html

      - name: Run Linter
        run: |
          ./flake.sh

      - name: Send Codecov
        uses: codecov/codecov-action@v2
        with: 
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
