name: Tests Py 3.11

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install pytest
          pip install pytest-cov
          pip install tensorflow
          pip install ray
          pip install scikit-learn
          pip install GPUtil

      - name: Install DRYML
        run: |
          python setup.py install

      - name: Run Tests
        run: |
          ./tests.sh --cov-report=xml --cov-report=html

      - name: Run Linter
        run: |
          ./flake.sh

      - name: Send Codecov
        uses: codecov/codecov-action@v2
        with: 
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
